databases:
  - name: QualityBeacon
    databaseName: quality_beacon_db
    user: quality_beacon_user

services:
  - type: web
    name: QualityBeacon
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn QualityBeacon.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: QualityBeacon
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4